language: python
python:
  - "3.9"
#  - "3.7"
install: "pip install -r requirements.txt"
script: 
  - py.test --cov --cov-report=xml owm tests -vv
  - sonar-scanner
after_success:
  - coveralls
addons:
  sonarcloud:
    organization: park-hyunsung
    token:
      secure: SONAR_TOKEN=5625678cb29add11c1eab9a3ae4b9367c788476a # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
